; VehicleLogger — Тестовый стенд с веб-дашбордом
; Прошивка: pio run -t upload
; Файловая система: pio run -t uploadfs
; Serial Monitor: pio device monitor

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    me-no-dev/ESPAsyncWebServer @ ^1.2.4
    me-no-dev/AsyncTCP @ ^1.1.1
    bblanchon/ArduinoJson @ ^7.0.0
    mikalhart/TinyGPSPlus @ ^1.1.0
